### ISSUE TITLE
Single Serving: Rubric Task List

### ISSUE THREAD

**Issue by jgagne** [MatthewTCronin/comedy-genres#1]
# Single Serving
## Rubric Task List

5 tasks (`20 points` each) with 1 extra credit task.

### Best Practices

`100 points`

- [x] Mobile-first and friendly
  - Use of a mobile-first, single-column layout for small screens, with a `max-width` and centered layout for wider screens.
- [x] Optimize all images
  - [Squoosh](https://squoosh.app): Use `MozJPEG` to optimize JPGs and use `OptiPNG` to optimize PNGs. (You may resize an image in Squoosh as well if needed.)
  - [ImageOptim](https://imageoptim.com/mac): Enable all image optimizations options (specifically `Guetzli`) via `ImageOptim` > `Preferences…` > `Enable` (left sidebar in General settings).
  - *Note:* Aim for an optimized file size around `150 KB` and below (max `200 KB`).
- [x] Validate all HTML, CSS, and color contrast
  - [Validate HTML](https://validator.w3.org/nu/) (No errors; warnings are ok, but try to resolve.)
  - [Validate CSS](http://jigsaw.w3.org/css-validator/) (No errors; warnings are ok, but try to resolve.)
  - [Color Contrast Accessibility Validator](https://color.a11y.com/) (All color combinations should pass: *Congratulations! No automated color contrast issues found on the webpage tested.*)
- [x] Audit performance, accessibility, best practices, and SEO of all pages.
  - [Measure](https://web.dev/measure/) and score 92 or above in all four categories.
- [x] Add a *description* and *URL* to the About section of your GitHub repo.
  - Share URL in `04-single-serving` channel
  - Repo should contain only essential files, and remember to use lowercase naming:
    - `index.html`
    - `css` (folder containing an external stylesheet)
      - For example: `main.css`
    - `img` (folder containing images)
      - For example: `self-portrait.jpg`
    - `README.md`
      - Update with a proper heading (title) and paragraph (description) using [Markdown](https://www.markdownguide.org/basic-syntax/).

### Extra Credit

`20 points`

- [x] Use of single (or more) web font from Google Fonts, with a web-safe [CSS font stack](http://www.cssfontstack.com).

**Comment by jgagne** [comment]
- [ ] Consider resizing display text size (Comedy Genres A Pictoral Informative Gallery) to work mobile first, then use a breakpoint to increase the font size, as we did in the previous project.
  - Also, I think you mean "Pictorial" instead of "Pictoral".
- [x] `images/ComedyBackdrop-01.jpg` should be exported and saved as a `.png` instead of a `.jpg`, as it's an illustration and not a photograph.
- [x] Please, revisit: Add a URL to the About section of your GitHub repo task.
- [x] Please, revisit: Use of single (or more) web font from Google Fonts, with a web-safe CSS font stack task.
  - `"Open Sans"` is declared in your `main.css`, but the font style sheet is not linked in your `index.html`.

**Comment by MatthewTCronin** [comment]
Alright. Thank you Justin.

Matthew Cronin
Emmanuel College, Class of 2021
Accounting/Graphic Design Major
Cross-Country Team Captain
________________________________
